# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                     #
#     _____  _     _    _  _____ _____ _   _          _____ _____     #
#    |  __ \| |   | |  | |/ ____|_   _| \ | |   /\   |  __ \_   _|    #
#    | |__) | |   | |  | | |  __  | | |  \| |  /  \  | |__) || |      #
#    |  ___/| |   | |  | | | |_ | | | | . ` | / /\ \ |  ___/ | |      #
#    | |    | |___| |__| | |__| |_| |_| |\  |/ ____ \| |    _| |_     #
#    |_|    |______\____/ \_____|_____|_| \_/_/    \_\_|   |_____|    #
#                                                                     #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                     #
#      REMOVING ANY MANDATORY KEYS MAY RESULT IN A BROKEN PLUGIN      #
#                                                                     #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# OFF     - no messages will be logged
# SEVERE  - all messages greater or equal to level 1000 will be logged
# WARNING - all messages greater or equal to level 900 will be logged
# INFO    - all messages greater or equal to level 800 will be logged
# CONFIG  - all messages greater or equal to level 700 will be logged
# FINE    - all messages greater or equal to level 500 will be logged
# FINER   - all messages greater or equal to level 400 will be logged
# FINEST  - all messages greater or equal to level 300 will be logged
# ALL     - all messages will be logged
logging-level: 'ALL'

# the maintenance settings of this proxy
maintenance:
  # when enabled, only permitted users may join the proxy
  enabled: false
  # the message to display to non permitted players when maintenance is enabled
  message: '§lMaintenance'
  ignored: {}

# when enabled, marks this plugin as mysql supported and will affect non-mysql configuration
mysql-enabled: false

# the settings to use when no mysql connection is established
non-mysql:
  # when enabled the api will force to use these settings disregarding any mysql connection
  force: true
  # the prefix
  prefix: '§lMyPlugin  '
  # the chat color
  chat-color: GRAY
  # the message to display when performing an action without the required permissions
  player-no-permission-error-message: §l§cERROR! §r§cYou don't have permission to perform this action!
  # the message to display when a specified player was not found though is required to perform an action
  player-not-found-error-message: §l§cERROR! §r§cThe specified player could not be found!
  # the message to display when executing a command that can only be executed by a player
  command-only-player-error-message: §l§cERROR! §r§cThis command can only be executed by a player!
  # the message to display when an error occurs while executing a command
  command-error-message: §l§cERROR! §r§cError while executing command!
  # the message to display when while executing a command has been given invalid args
  command-invalid-args-error-message: §l§cERROR! §r§cInvalid arguments!
  # the message to display when an internal error occurs while executing a command
  command-internal-error-message: §l§cERROR! §r§cInternal error while executing command!
  # the time when a user unregisters after a certain time of disconnection
  user-timeout: 20